services:
  elasticmq:
    image: softwaremill/elasticmq
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    networks:
      - messagebridge-net

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"  # JMS
      - "8161:8161"    # Web Console
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    networks:
      - messagebridge-net

networks:
  messagebridge-net:
    driver: bridge
